version: '3'
services:
  goweather:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile.prod}
    image: ${DOCKERIMAGE:-goweatherimageprod}
    container_name: ${DOCKERCONT:-goweathercontprod}
    ports:
      - "8080:8080"
