// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/luis-olivetti/go-weather-city/internal/service"
	"github.com/luis-olivetti/go-weather-city/internal/usecase"
	"net/http"
)

// Injectors from wire.go:

func InitializeGetDataWithViaCepApiUseCase(client *http.Client) *usecase.GetDataWithViaCepApiUseCaseImpl {
	getDataWithViaCepApiUseCaseImpl := usecase.NewGetDataWithViaCepApiUseCaseImpl(client)
	return getDataWithViaCepApiUseCaseImpl
}

func InitializeGetTemperatureWithWeatherApiUseCase(client *http.Client) *usecase.GetTemperatureWithWeatherApiUseCaseImpl {
	getTemperatureWithWeatherApiUseCaseImpl := usecase.NewGetTemperatureWithWeatherApiUseCaseImpl(client)
	return getTemperatureWithWeatherApiUseCaseImpl
}

func InitializeGetCityAndWeatherByZipCode(viaCepUseCase usecase.GetDataWithViaCepApiUseCaseInterface, weatherUseCase usecase.GetTemperatureWithWeatherApiUseCaseInterface) *service.GetCityAndWeatherByZipCodeImpl {
	getCityAndWeatherByZipCodeImpl := service.NewGetCityAndWeatherByZipCodeImpl(viaCepUseCase, weatherUseCase)
	return getCityAndWeatherByZipCodeImpl
}
